#[[

Windows-specific FFmpeg build configuration.

This file configures FFmpeg builds for Windows, supporting both:
1. MSYS2/MinGW toolchain (recommended)
2. MSVC toolchain (with additional setup required)
3. Cross-compilation from Linux/macOS

Requirements:
- For MSYS2: MSYS2 installation with MinGW-w64 toolchain
- For MSVC: Visual Studio with C++ tools
- For cross-compilation: MinGW-w64 cross-compiler

]]

cmake_minimum_required (VERSION 3.22 FATAL_ERROR)

include_guard (GLOBAL)

message (STATUS "Configuring FFmpeg Windows build...")

# Windows-specific configure options
set (WINDOWS_CONFIGURE_EXTRA_ARGS
     "--enable-cross-compile"
     "--target-os=win32"
     "--arch=x86_64"
     "--disable-w32threads"  # Use pthreads instead
     "--enable-pthreads"
     "--disable-cuda-nvcc"   # Disable NVIDIA CUDA unless specifically needed
     "--disable-libnpp")

# Use MSYS2 configuration if detected (MSYS2_ROOT_PATH set in main CMakeLists.txt)
if (FFMPEG_WINDOWS_USE_MSYS2 AND MSYS2_ROOT_PATH)
    message (STATUS "Using MSYS2/MinGW toolchain for Windows build")
    message (STATUS "MSYS2 root: ${MSYS2_ROOT_PATH}")
    
    find_program (MSYS2_CC
                  NAMES gcc.exe x86_64-w64-mingw32-gcc.exe
                  PATHS "${MSYS2_ROOT_PATH}/mingw64/bin" "${MSYS2_ROOT_PATH}/usr/bin"
                  NO_DEFAULT_PATH
                  DOC "MinGW GCC compiler")
    
    find_program (MSYS2_CXX
                  NAMES g++.exe x86_64-w64-mingw32-g++.exe
                  PATHS "${MSYS2_ROOT_PATH}/mingw64/bin" "${MSYS2_ROOT_PATH}/usr/bin"
                  NO_DEFAULT_PATH
                  DOC "MinGW G++ compiler")
    
    if (NOT MSYS2_CC OR NOT MSYS2_CXX)
        message (WARNING "MinGW compilers not found. Install with: pacman -S mingw-w64-x86_64-toolchain")
        message (WARNING "Falling back to standard Windows build.")
        set (FFMPEG_WINDOWS_USE_MSYS2 OFF)
    else()
        message (STATUS "Found MinGW GCC: ${MSYS2_CC}")
        message (STATUS "Found MinGW G++: ${MSYS2_CXX}")
        
        list (APPEND WINDOWS_CONFIGURE_EXTRA_ARGS
              "--toolchain=gcc"
              "--cc=${MSYS2_CC}"
              "--cxx=${MSYS2_CXX}")
    endif()
endif()

if (NOT FFMPEG_WINDOWS_USE_MSYS2 OR NOT MSYS2_ROOT_PATH)
    if (MSVC)
        message (STATUS "Using MSVC toolchain for Windows build")
        message (WARNING "MSVC builds require manual configuration. Consider using MSYS2 instead.")
        
        list (APPEND WINDOWS_CONFIGURE_EXTRA_ARGS
              "--toolchain=msvc")
             
    else()
        # Assume MinGW or cross-compilation
        message (STATUS "Using default Windows build configuration")
        message (WARNING "Build may fail without MSYS2. Consider installing MSYS2 for better Windows support.")
    endif()
endif()

# Configure build
if (PROJECT_IS_TOP_LEVEL)
    set (all_flag ALL)
else ()
    unset (all_flag)
endif ()

set (windows_output_dir "${ffmpeg_output_dir}/windows")

message (DEBUG "Windows output directory: ${windows_output_dir}")

# Use standard functions like other platforms
preconfigure_ffmpeg_build (
    SOURCE_DIR "${FFMPEG_SOURCE_DIR}" 
    OUTPUT_DIR "${windows_output_dir}"
    EXTRA_ARGS ${WINDOWS_CONFIGURE_EXTRA_ARGS})

create_ffmpeg_build_target (
    SOURCE_DIR "${FFMPEG_SOURCE_DIR}" 
    OUTPUT_DIR "${windows_output_dir}"
    BUILD_TARGET ffmpeg_build_windows
    ${all_flag})

# Note: avconfig.h will be copied after the build completes
# since it's generated by the configure script
file (MAKE_DIRECTORY "${ffmpeg_output_dir}/include/libavutil")

add_dependencies (ffmpeg ffmpeg_build_windows)

# Copy avconfig.h after the build completes (since it's generated by configure)
add_custom_command(
    TARGET ffmpeg_build_windows POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "${FFMPEG_SOURCE_DIR}/libavutil/avconfig.h"
        "${ffmpeg_output_dir}/include/libavutil/avconfig.h"
    COMMENT "Copying generated avconfig.h for Windows build"
    VERBATIM)

message (STATUS "Windows FFmpeg build configured successfully") 